robots:
  - name: robot1
    x: 0.5
    y: 1.0
    z: 0.01
  - name: robot2
    x: -1.0
    y: 2.5
    z: 0.01
obstacles:
  - name: obstacle1
    model: model_box.sdf
    x: 2.0
    y: 3.0
    z: 0.5
  - name: obstacle2
    model: model_box.sdf
    x: -2.5
    y: 0.0
    z: 0.5

